# Generated by Django 5.2.7 on 2025-10-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llmproxy', '0002_conv_updates'),
        ('llmproxy', '0002_conversation_user'),
    ]

    operations = [
    ]
