# Generated by Django 5.2.7 on 2025-10-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llmproxy', '0003_merge_0002_conv_updates_0002_conversation_user'),
        ('llmproxy', '0003_pdf_context'),
    ]

    operations = [
    ]
